### ISSUE TITLE
Problem about fixed vertices.

### ISSUE THREAD

**Issue by zxxx200104** [kahypar/kahypar#119]
I have encountered a problem, which can be roughly described by the following picture. When I divide the hypergraph into two parts and set the part_weights = {3, 2}, I can get the division result as shown in the left image, when I set these five vertices as fixed vertices, and add another 5 Vertices, re-divide, set part_weights = {6, 4}, I may get the result as shown on the right, part_weights = {4, 6}. the output imbalance is very large. And the result I expect is the bottom picture, the output imbalance is less than 0.
Thanks very much!

![image](https://user-images.githubusercontent.com/93234128/182562801-30da7405-34d9-45d2-9ff2-bdf4735b151d.png)

**Comment by SebastianSchlag** [comment]
Hi,
First of all sorry for the delayed response. I've been very busy the last couple of days. Could you share the hypergraph that you are trying to partition as well as the kahypar configuration & command line options that you are using? 

From a balancing perspective both solutions are identical (one block has 4 vertices, the other one has 6), right?  Does the problem also happen for `k=2` or only for `k>2`?  What could be happening here is that the block sizes somehow get permuted during recursive bipartitioning such that in the end the given upper bounds are respected, but the blocks (and their weights) are a permutation of the input part weights. 

@kittobi1992 Have you noticed something similar before?

**Comment by zxxx200104** [comment]
Hi，
Great to receive your reply.Here is the hypergraph I use, with fixed vertices, and the output. It can be seen from the log file that Imbalance=0.841359. It reversed the maximum weight of the two parts.
command line is  ./kahypar/application/KaHyPar -h ../special_instances/hypergraph.hgr -k 2 -p ../config/cut_rKaHyPar_sea20.ini --use-individual-part-weights true --part-weights 18129 34689 -f ../special_instances/fixed.hgr -e 0 -m recursive -o cut -w true
[case.zip](https://github.com/kahypar/kahypar/files/9281422/case.zip)

**Comment by zxxx200104** [comment]
Hi，@SebastianSchlag 
Did you find the problem?

**Comment by SebastianSchlag** [comment]
Sorry, I haven’t found the time to look into this. I’ll get back to you as soon as possible.

**Comment by SebastianSchlag** [comment]
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+                    _  __     _   _       ____                               +
+                   | |/ /__ _| | | |_   _|  _ \ __ _ _ __                    +
+                   | ' // _` | |_| | | | | |_) / _` | '__|                   +
+                   | . \ (_| |  _  | |_| |  __/ (_| | |                      +
+                   |_|\_\__,_|_| |_|\__, |_|   \__,_|_|                      +
+                                    |___/                                    +
+                 Karlsruhe Hypergraph Partitioning Framework                 +
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
*******************************************************************************
*                            Partitioning Context                             *
*******************************************************************************
Partitioning Parameters:
  Hypergraph:                         /Users/sebastianschlag/Downloads/case/hypergraph.hgr
  Partition File:                     /Users/sebastianschlag/Downloads/case/hypergraph.hgr.part2.epsilon0..seed-1.KaHyPar
  Fixed Vertex File:                  /Users/sebastianschlag/Downloads/case/fixed.hgr
  Mode:                               recursive
  Objective:                          cut
  k:                                  2
  epsilon:                            0
  seed:                               -1
  # V-cycles:                         0
  time limit:                         -1s
  hyperedge size threshold:           4294967295
  use individual block weights:       true
  L_opt0:                             18129
  L_opt1:                             34689
  L_max0:                             18129
  L_max1:                             34689
-------------------------------------------------------------------------------
Preprocessing Parameters:
  enable deduplication:               false
  enable min hash sparsifier:         true
  enable community detection:         true
-------------------------------------------------------------------------------
MinHash Sparsifier Parameters:
  max hyperedge size:                 1200
  max cluster size:                   10
  min cluster size:                   2
  number of hash functions:           5
  number of combined hash functions:  100
  active at median net size >=:       28
  sparsifier is active:               false
-------------------------------------------------------------------------------
Community Detection Parameters:
  use community detection in IP:      false
  maximum louvain-pass iterations:    100
  minimum quality improvement:        0.0001
  graph edge weight:                  uniform
  reuse community structure:          false
-------------------------------------------------------------------------------
Coarsening Parameters:
  Algorithm:                          heavy_lazy
  max-allowed-weight-multiplier:      3.25
  contraction-limit-multiplier:       160
  hypernode weight fraction:          0.0101563
  max. allowed hypernode weight:      512
  contraction limit:                  320
  Rating Parameters:
    Rating Function:                  heavy_edge
    Use Community Structure:          true
    Heavy Node Penalty:               multiplicative
    Acceptance Policy:                best
    Partition Policy:                 normal
    Fixed Vertex Acceptance Policy:   free_vertex_only
-------------------------------------------------------------------------------
Initial Partitioning Parameters:
  # IP trials:                        20
  Mode:                               direct
  Technique:                          flat
  Algorithm:                          pool
  Bin Packing algorithm:              worst_fit
    early restart on infeasible:      true
    late restart on infeasible:       true
-------------------------------------------------------------------------------
Local Search Parameters:
  Algorithm:                          twoway_fm_hyperflow_cutter
  iterations per level:               2147483647
  stopping rule:                      adaptive_opt
  adaptive stopping alpha:            1
  Flow Refinement Parameters:
    execution policy:                 exponential
-------------------------------------------------------------------------------


********************************************************************************
*                                    Input                                     *
********************************************************************************
Hypergraph Information
Name : hypergraph.hgr
Type: edgeWeights=false nodeWeights=true
# HNs : 649 # HEs : 773 # pins: 2004
HE size             HE weight           HN degree           HN weight
| min= 1            | min= 1            | min= 1            | min= 1
| Q1 = 2            | Q1 = 1            | Q1 = 2            | Q1 = 1
| med= 2            | med= 1            | med= 3            | med= 1
| Q3 = 3            | Q3 = 1            | Q3 = 4            | Q3 = 1
| max= 28           | max= 1            | max= 7            | max= 1256
| avg= 2.5925       | avg= 1            | avg= 3.08783      | avg= 77.5254
| sd = 2.06207      | sd = 0            | sd = 1.10134      | sd = 207.446

********************************************************************************
*                          Top Level Preprocessing..                           *
********************************************************************************
Performing single-node HE removal:
  # removed hyperedges with |e|=1 =  131
  ===> 1 unconnected HNs could have been removed
--------------------------------------------------------------------------------
================================================================================
Recursive Bisection No. 1 : Computing blocks ( 0 .. 1 )
L_max0: 18130
L_max1: 34690
================================================================================
********************************************************************************
*                               Preprocessing...                               *
********************************************************************************
Performing community detection:
  hypergraph is a graph = false
  # communities         = 20
  modularity            = 0.809653
********************************************************************************
*                                Coarsening...                                 *
********************************************************************************
[ ########################################################################### ] (100% - 286/286) 0 s - Current Objective: 0
Hypergraph Information
Name : Coarsened Hypergraph
Type: edgeWeights=true nodeWeights=true
# HNs : 286 # HEs : 274 # pins: 742
HE size             HE weight           HN degree           HN weight
| min= 2            | min= 1            | min= 1            | min= 1
| Q1 = 2            | Q1 = 1            | Q1 = 2            | Q1 = 1
| med= 2            | med= 1            | med= 2            | med= 1
| Q3 = 3            | Q3 = 1            | Q3 = 3            | Q3 = 236
| max= 11           | max= 1            | max= 6            | max= 1256
| avg= 2.70803      | avg= 1            | avg= 2.59441      | avg= 174.654
| sd = 1.27334      | sd = 0            | sd = 1.05457      | sd = 284.464

********************************************************************************
*                           Initial Partitioning...                            *
********************************************************************************
Calling Initial Partitioner: flat direct pool (k= 2 , epsilon= 0.0573962 )
Minimum Quality   = [ Cut= 11 - Imbalance= 0.001138 - Algorithm= bin_packing ]
Maximum Quality   = [ Cut= 28 - Imbalance= 0.00138321 - Algorithm= random ]
Minimum Imbalance = [ Cut= 14 - Imbalance= 0.000150349 - Algorithm= greedy_round_maxnet ]
Maximum Imbalance = [ Cut= 13 - Imbalance= 0.00637479 - Algorithm= greedy_global_maxnet ]
==> Best Quality  = [ Cut= 11 - Imbalance= 0.001138 - Algorithm= bin_packing ]
Initial Partitioning Result:
Initial cut       = 11
Initial imbalance = 0.001138
Initial part sizes and weights:
|part 0 | = 198  w( 0 ) = 16715
|part 1 | =  88  w( 1 ) = 33236
Target weights:  (RB): w(0)= 18130 w(1)= 34690

********************************************************************************
*                               Local Search...                                *
********************************************************************************
[ ########################################################################### ] (100% - 286/286) 0 s - Current Objective: 11
Local Search Result:
Final cut       = 11
Final imbalance = 0.001138
Final part sizes and weights:
|part 0 | = 198  w( 0 ) = 16715
|part 1 | =  88  w( 1 ) = 33236

================================================================================
Maximum-Weighted Bipartite Matching
================================================================================
Partitioning objective of hypergraph without fixed vertices:  cut = 11
Computed Permutation:
Block 1 assigned to fixed vertices with id 0 with weight 0
Block 0 assigned to fixed vertices with id 1 with weight 37
Weight of matching  : 37
Lower Bound ( cut ) : 11
Upper Bound ( cut ) : 110
Final cut = 110 - 37 = 73
================================================================================
********************************************************************************
*                             Partitioning Result                              *
********************************************************************************
Objectives:
Hyperedge Cut  (minimize) = 63
SOED           (minimize) = 126
(k-1)          (minimize) = 63
Absorption     (maximize) = 611.098
Imbalance                 = 0.840477

Partition sizes and weights:
|part 0 | = 218  w( 0 ) = 33366
|part 1 | = 431  w( 1 ) = 16948

Timings:
Partition time                     = 0.0252925 s
  + Preprocessing                  = 0.00049025 s
    | min hash sparsifier          = 0 s
    | community detection          = 0.00049025 s
  + Coarsening                     = 6.0834e-05 s
        | bisection 1 ( 0 , 1 )        = 6.0834e-05 s
  + Initial Partitioning           = 0.0227717 s
        | bisection 1 ( 0 , 1 )        = 0.0227717 s
  + Local Search                   = 0.000200625 s
           | flow refinement       = 0  s
        | bisection 1 ( 0 , 1 )        = 0.000200625 s
  + Postprocessing                 = 0 s
    | undo sparsifier              = 0 s
```

@kittobi1992 it looks like this has something to do with the maximum weighted bipartite matching algorithm. If you look at the results of local search, you can see that the given upper-bound block weights are actually respected:  

```
Final imbalance = 0.001138
Final part sizes and weights:
|part 0 | = 198  w( 0 ) = 16715
|part 1 | =  88  w( 1 ) = 33236
```

but after the bipartite matching the blocks are actually switched. Could you please take a look at this?

**Comment by kittobi1992** [comment]
I fixed the isssue. The algorithm that matches the fixed vertices to the blocks has not considered the individual block weights (previously it assumed that each block has the same maximum weight limit).

**Comment by zxxx200104** [comment]
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
+                    _  __     _   _       ____                               + 
+                   | |/ /__ _| | | |_   _|  _ \ __ _ _ __                    + 
+                   | ' // _` | |_| | | | | |_) / _` | '__|                   + 
+                   | . \ (_| |  _  | |_| |  __/ (_| | |                      + 
+                   |_|\_\__,_|_| |_|\__, |_|   \__,_|_|                      + 
+                                    |___/                                    + 
+                 Karlsruhe Hypergraph Partitioning Framework                 + 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
*******************************************************************************
*                            Partitioning Context                             *
*******************************************************************************
Partitioning Parameters:
  Hypergraph:                         ../special_instances/hypergraph.hgr
  Partition File:                     ../special_instances/hypergraph.hgr.part2.epsilon0..seed-1.KaHyPar
  Fixed Vertex File:                  ../special_instances/fixed.hgr
  Mode:                               recursive
  Objective:                          cut
  k:                                  2
  epsilon:                            0
  seed:                               -1
  # V-cycles:                         0
  time limit:                         -1s
  hyperedge size threshold:           4294967295
  use individual block weights:       true
  L_opt0:                             18129
  L_opt1:                             34689
  L_max0:                             18129
  L_max1:                             34689
-------------------------------------------------------------------------------
Preprocessing Parameters:
  enable deduplication:               false
  enable min hash sparsifier:         true
  enable community detection:         true
-------------------------------------------------------------------------------
MinHash Sparsifier Parameters:
  max hyperedge size:                 1200
  max cluster size:                   10
  min cluster size:                   2
  number of hash functions:           5
  number of combined hash functions:  100
  active at median net size >=:       28
  sparsifier is active:               false
-------------------------------------------------------------------------------
Community Detection Parameters:
  use community detection in IP:      false
  maximum louvain-pass iterations:    100
  minimum quality improvement:        0.0001
  graph edge weight:                  uniform
  reuse community structure:          false
-------------------------------------------------------------------------------
Coarsening Parameters:
  Algorithm:                          heavy_lazy
  max-allowed-weight-multiplier:      3.25
  contraction-limit-multiplier:       160
  hypernode weight fraction:          0.0101563
  max. allowed hypernode weight:      512
  contraction limit:                  320
  Rating Parameters:
    Rating Function:                  heavy_edge
    Use Community Structure:          true
    Heavy Node Penalty:               multiplicative
    Acceptance Policy:                best
    Partition Policy:                 normal
    Fixed Vertex Acceptance Policy:   free_vertex_only
-------------------------------------------------------------------------------
Initial Partitioning Parameters:
  # IP trials:                        20
  Mode:                               direct
  Technique:                          flat
  Algorithm:                          pool
  Bin Packing algorithm:              worst_fit
    early restart on infeasible:      true
    late restart on infeasible:       true
-------------------------------------------------------------------------------
Local Search Parameters:
  Algorithm:                          twoway_fm_hyperflow_cutter
  iterations per level:               2147483647
  stopping rule:                      adaptive_opt
  adaptive stopping alpha:            1
  Flow Refinement Parameters:
    execution policy:                 exponential
-------------------------------------------------------------------------------
 
******************************************************************************** 
*                             Partitioning Result                              * 
******************************************************************************** 
Objectives: 
Hyperedge Cut  (minimize) = 81 
SOED           (minimize) = 162 
(k-1)          (minimize) = 81 
Absorption     (maximize) = 604.033 
Imbalance                 = 0.889073 

Partition sizes and weights:  
|part 0 | = 319  w( 0 ) = 34247 
|part 1 | = 330  w( 1 ) = 16067 

Timings: 
Partition time                     = 0.015544 s 
  + Preprocessing                  = 0.0003094 s 
    | min hash sparsifier          = 0 s 
    | community detection          = 0.0003094 s 
  + Coarsening                     = 2.33e-05 s 
        | bisection 1 ( 0 , 1 )        = 2.33e-05 s 
  + Initial Partitioning           = 0.0148405 s 
        | bisection 1 ( 0 , 1 )        = 0.0148405 s 
  + Local Search                   = 1.24e-05 s 
           | flow refinement       = 0  s 
        | bisection 1 ( 0 , 1 )        = 1.24e-05 s 
  + Postprocessing                 = 0 s 
    | undo sparsifier              = 0 s 
Hi, @kittobi1992 
I modified the code as you suggested, but I still get this error when I run the code.Could you please take another look at this?

**Comment by zxxx200104** [comment]
Partitioning Result 
Objectives: 
Hyperedge Cut  (minimize) = 81 
SOED           (minimize) = 162 
(k-1)          (minimize) = 81 
Absorption     (maximize) = 604.033 
Imbalance                 = 0.889073 

Partition sizes and weights:  
|part 0 | = 319  w( 0 ) = 34247 
|part 1 | = 330  w( 1 ) = 16067 

Timings: 
Partition time                     = 0.015544 s 
  + Preprocessing                  = 0.0003094 s 
    | min hash sparsifier          = 0 s 
    | community detection          = 0.0003094 s 
  + Coarsening                     = 2.33e-05 s 
        | bisection 1 ( 0 , 1 )        = 2.33e-05 s 
  + Initial Partitioning           = 0.0148405 s 
        | bisection 1 ( 0 , 1 )        = 0.0148405 s 
  + Local Search                   = 1.24e-05 s 
           | flow refinement       = 0  s 
        | bisection 1 ( 0 , 1 )        = 1.24e-05 s 
  + Postprocessing                 = 0 s 
    | undo sparsifier              = 0 s** 
 
Hi, @kittobi1992
I modified the code as you suggested, but I still get this error when I run the code.Could you please take another look at this?

**Comment by kittobi1992** [comment]
Hi,
I used the wrong index in my previous fix (j instead of i). Unlikely, it worked on my machine ...
I created the branch [fixed_vertices_with_individual_part_weights](/kahypar/kahypar/tree/fixed_vertices_with_individual_part_weights) and provide a new fix for the issue. If this fix works for you, we will merge it immediately to master.

**Comment by zxxx200104** [comment]
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
+                    _  __     _   _       ____                               + 
+                   | |/ /__ _| | | |_   _|  _ \ __ _ _ __                    + 
+                   | ' // _` | |_| | | | | |_) / _` | '__|                   + 
+                   | . \ (_| |  _  | |_| |  __/ (_| | |                      + 
+                   |_|\_\__,_|_| |_|\__, |_|   \__,_|_|                      + 
+                                    |___/                                    + 
+                 Karlsruhe Hypergraph Partitioning Framework                 + 
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ 
*******************************************************************************
*                            Partitioning Context                             *
*******************************************************************************
Partitioning Parameters:
  Hypergraph:                         
  Partition File:                     
  Mode:                               recursive
  Objective:                          cut
  k:                                  2
  epsilon:                            0
  seed:                               -1
  # V-cycles:                         0
  time limit:                         -1s
  hyperedge size threshold:           4294967295
  use individual block weights:       true
  L_opt0:                             500869
  L_opt1:                             737888
  L_max0:                             500869
  L_max1:                             737888
-------------------------------------------------------------------------------
Preprocessing Parameters:
  enable deduplication:               false
  enable min hash sparsifier:         true
  enable community detection:         true
-------------------------------------------------------------------------------
MinHash Sparsifier Parameters:
  max hyperedge size:                 1200
  max cluster size:                   10
  min cluster size:                   2
  number of hash functions:           5
  number of combined hash functions:  100
  active at median net size >=:       28
  sparsifier is active:               false
-------------------------------------------------------------------------------
Community Detection Parameters:
  use community detection in IP:      false
  maximum louvain-pass iterations:    100
  minimum quality improvement:        0.0001
  graph edge weight:                  uniform
  reuse community structure:          false
-------------------------------------------------------------------------------
Coarsening Parameters:
  Algorithm:                          heavy_lazy
  max-allowed-weight-multiplier:      3.25
  contraction-limit-multiplier:       160
  hypernode weight fraction:          0.0101563
  max. allowed hypernode weight:      12363
  contraction limit:                  320
  Rating Parameters:
    Rating Function:                  heavy_edge
    Use Community Structure:          true
    Heavy Node Penalty:               multiplicative
    Acceptance Policy:                best
    Partition Policy:                 normal
    Fixed Vertex Acceptance Policy:   free_vertex_only
-------------------------------------------------------------------------------
Initial Partitioning Parameters:
  # IP trials:                        20
  Mode:                               direct
  Technique:                          flat
  Algorithm:                          pool
  Bin Packing algorithm:              worst_fit
    early restart on infeasible:      true
    late restart on infeasible:       true
-------------------------------------------------------------------------------
Local Search Parameters:
  Algorithm:                          twoway_fm_hyperflow_cutter
  iterations per level:               2147483647
  stopping rule:                      adaptive_opt
  adaptive stopping alpha:            1
  Flow Refinement Parameters:
    execution policy:                 exponential
-------------------------------------------------------------------------------
 
******************************************************************************** 
*                             Partitioning Result                              * 
******************************************************************************** 
Objectives: 
Hyperedge Cut  (minimize) = 1383 
SOED           (minimize) = 2766 
(k-1)          (minimize) = 1383 
Absorption     (maximize) = 27469 
Imbalance                 = 0.468148 

Partition sizes and weights:  
|part 0 | = 10234  w( 0 ) = 735350 
|part 1 | = 16372  w( 1 ) = 481880 

Timings: 
Partition time                     = 0.154144 s 
  + Preprocessing                  = 0.093979 s 
    | min hash sparsifier          = 0 s 
    | community detection          = 0.093979 s 
  + Coarsening                     = 0.0349374 s 
        | bisection 1 ( 0 , 1 )        = 0.0349374 s 
  + Initial Partitioning           = 0.0815957 s 
        | bisection 1 ( 0 , 1 )        = 0.0815957 s 
  + Local Search                   = 0.041969 s 
           | flow refinement       = 0.0019165  s 
        | bisection 1 ( 0 , 1 )        = 0.041969 s 
  + Postprocessing                 = 0 s 
    | undo sparsifier              = 0 s
``` 

Hi, @kittobi1992 
I changed j to i and errors are less likely to occur, but errors still occur when I divide a larger example.

**Comment by zxxx200104** [comment]
Hi, @kittobi1992 
This is the case where I get an error after changing j to i.
command line is
`./kahypar/application/KaHyPar -h ../special_instances/hypergraph.hgr -k 2 -p ../config/cut_rKaHyPar_sea20.ini --use-individual-part-weights true --part-weights 5537 10596 -f ../special_instances/fixed.hgr -e 0 -m recursive -o cut`
[case2.zip](https://github.com/kahypar/kahypar/files/9367040/case2.zip)

**Comment by SebastianSchlag** [comment]
Thanks for your update @zxxx200104. @kittobi1992 is on vacation for a couple of days, but he'll check in again once he is back.

**Comment by kittobi1992** [comment]
Hi @zxxx200104,
I finally found the source of the bug and fixed it. I was able to reproduce the bug on a small test graph and added a test case for it. If the fix is working for you now, we will merge it to the master branch.

**Comment by zxxx200104** [comment]
Hi @kittobi1992 
Thank you very much for taking the time to track down this issue, this modification leads to a reasonable solution in most cases. In addition, I still have a question about this issue. The algorithm seems to divide the vertices without fixed blocks separately and then match them with fixed blocks. In this case, the inherent connection relationship between fixed blocks is not considered. Will the result get worse? For example, there is a wire net that has connections between fixed blocks and non-fixed blocks. If he has been cut between fixed blocks, whether he cuts the net in the non-fixed block has no effect on the whole. But in fact the algorithm does not take advantage of this information when dividing non-fixed blocks.

**Comment by kittobi1992** [comment]
Hi @zxxx200104,
that is a good question. If you compute a k-way partition via recursive bipartitioning, you have two options: (i) Either you include the fixed vertices or (ii) you remove them and use our matching algorithm. For the top-level bipartition in the first case, you have to preassign the fixed vertex blocks to one of the two blocks. This can be done e.g. by assigning the fixed vertices of the blocks 1 to k/2 - 1 to the the first block and fixed vertices of the blocks k/2 to k to the second block. By doing so, you preserve the connectivity information of the hypergraph, but this may lead to bad decision in later steps of bipartitioning process. In our experiments, we found out that second approach works better. Although you do not consider the connectivity information during recursive bipartitioning, they will be considered again in the matching algorithm. But I agree with you that is not an optimal solution.

I saw that you run KaHyPar in the recursive bipartitioning mode. I do not precisely know your setting, but I would suggest to use the direct k-way partitioning mode (-m direct). The direct k-way mode only uses recursive bipartitioning in the initial partitioning phase. During coarsening and refinement, fixed vertices are still present and bad decision that are done in the initial partitioning phase could be repaired during uncoarsening. It might be worth to try it.

**Comment by zxxx200104** [comment]
Hi @kittobi1992 
Thanks for your answer,use the direct k-way partitioning mode does take more time but does get a higher quality solution,

**Comment by SebastianSchlag** [comment]
Yes, direct k-way partitioning is more expensive than recursive bipartitioning, but as @kittobi1992 said, in all our experimental evaluations it turned out to be the superior approach in terms of solution quality.

**Comment by zxxx200104** [comment]
Yes, thanks again for taking the time to follow up on this issue.
